### ISSUE TITLE
reading from stdin is broken in linux

### ISSUE THREAD

**Issue by haraldschilly** [opentimestamps/python-opentimestamps#31]
Well, this doesn't work. (Ubuntu linux, bash, python 3.5)

```
$ echo $LANG
en_US.UTF-8

$ echo "test" | ots verify test.ots -f -
Traceback (most recent call last):
  File "/home/xxx/.local/bin/ots", line 11, in <module>
    sys.exit(main())
  File "/home/xxx/.local/lib/python3.5/site-packages/otsclient/ots.py", line 34, in main
    args.cmd_func(args)
  File "/home/xxx/.local/lib/python3.5/site-packages/otsclient/cmds.py", line 482, in verify_command
    actual_file_digest = detached_timestamp.file_hash_op.hash_fd(args.target_fd)
  File "/home/xxx/.local/lib/python3.5/site-packages/opentimestamps/core/op.py", line 301, in hash_fd
    hasher.update(chunk)
TypeError: Unicode-objects must be encoded before hashing
```

A naive fix would be to change that line in op.py where `hash_fd` is to: `hasher.update(chunk.encode('utf8'))`, but then it's broken when reading from a file. I have the feeling there could be a common solution to that, but I don't know it.

**Comment by petertodd** [comment]
Turns out the root cause of this problem is a bug in argparse itself: https://bugs.python.org/issue14156

This also means that all our uses of `argparse.FileType` are broken in the same way. For example:

```
$ cat README.md.ots | /home/user/.local/bin/ots info -
Traceback (most recent call last):
  File "/home/user/.local/bin/ots", line 11, in <module>
    load_entry_point('opentimestamps-client', 'console_scripts', 'ots')()
  File "/home/user/src/ots/opentimestamps-client/otsclient/ots.py", line 34, in main
    args.cmd_func(args)
  File "/home/user/src/ots/opentimestamps-client/otsclient/cmds.py", line 499, in info_command
    detached_timestamp = DetachedTimestampFile.deserialize(ctx)
  File "/usr/local/lib/python3.5/dist-packages/opentimestamps/core/timestamp.py", line 329, in deserialize
    ctx.assert_magic(cls.HEADER_MAGIC)
  File "/usr/local/lib/python3.5/dist-packages/opentimestamps/core/serialize.py", line 216, in assert_magic
    actual_magic = self.fd.read(len(expected_magic))
  File "/usr/lib/python3.5/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbf in position 23: invalid start byte
```

Given that the bug has remained open for five years, the fastest way to fix this is probably to write a replacement for `FileType`. :/

Kinda crazy really that this is broken as usage of `-` as an alias for stdin/stdout is really common, as are binary files.

**Comment by petertodd** [comment]
Note, you actually opened this in the wrong repo, so I've opened a new issue to track this: https://github.com/opentimestamps/opentimestamps-client/issues/86
