### ISSUE TITLE
Crash on signing large code rebase

### ISSUE THREAD

**Issue by AdamISZ** [opentimestamps/python-opentimestamps#41]
Since it's been a couple of years since I hooked up OTS, this could very likely be an already fixed issue, in which case I'll close it ofc, but just thought I should drop this traceback in case it isn't a known issue:

```
Traceback (most recent call last):
  File "/home/adam/.local/bin/ots-git-gpg-wrapper", line 11, in <module>
    sys.exit(main())
  File "/home/adam/.local/lib/python3.5/site-packages/otsclient/git_gpg_wrapper.py", line 108, in main
    signed_commit_timestamp = Timestamp(hash_signed_commit(git_commit, gpg_sig))
  File "/home/adam/.local/lib/python3.5/site-packages/otsclient/git.py", line 27, in hash_signed_commit
    return OpSHA256()(OpSHA256()(git_commit) + OpSHA256()(gpg_sig))
  File "/home/adam/.local/lib/python3.5/site-packages/opentimestamps/core/op.py", line 133, in __call__
    raise MsgValueError("Message too long; %d > %d" % (len(msg), self.MAX_MSG_LENGTH))
opentimestamps.core.op.MsgValueError: Message too long; 4133 > 4096
error: gpg failed to sign the data
fatal: failed to write commit object

Could not apply a166035f6046aa0df194f12272f40090a6c9bc5f... fix wallet sync test bug
```

**Comment by petertodd** [comment]
Try a newer version; IIRC this is a known issue and is fixed.

**Comment by AdamISZ** [comment]
Will do, thanks.
